domain: charmed-osm.com

image: prod-comms.ps5.docker-registry.canonical.com/charmed-osm.com

env:
  - name: SENTRY_DSN
    value: https://41979fee12c9487786a237cd40d79f69@sentry.is.canonical.com//31

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'charmed-osm.com' ) {
      rewrite ^ https://charmed-osm.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
