name: PR checks
on: pull_request

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag charmed-osm-com .

      - name: Run image
        run: |
          docker run --detach --env SECRET_KEY=insecure_dev_key --network host charmed-osm-com
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost

  run-dotrun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dotrun
        run: |
          sudo snap install dotrun
          sudo chown root:root /

      - name: Install dependencies
        run: dotrun install

      - name: Build assets
        run: dotrun build

      - name: Test site
        run: |
          dotrun &
          curl --head --fail --retry-delay 2 --retry 30 --retry-connrefused http://localhost:8042

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black

      - name: Lint python
        run: yarn lint-python

  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install dependencies
        run: sudo pip3 install coverage

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Build resources
        run: yarn build

      - name: Run tests with coverage
        run: |
          SECRET_KEY=insecure_dev_key coverage run  --source=. -m unittest discover tests
          bash <(curl -s https://codecov.io/bash) -cF python

  check-inclusive-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          fail-on-error: true
